// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoX.Infrastructure.Database;

#nullable disable

namespace Plans.Infrastructure.Database.Migrations.Plans
{
    [DbContext(typeof(PlanShemeDbContext))]
    [Migration("20260104173501_Initial_Plans")]
    partial class Initial_Plans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Plans")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoX.Core.Entity.PlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Plans", "Plans");
                });

            modelBuilder.Entity("ToDoX.Core.Entity.TaskDescriptionBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskDescriptionBlocks", "Plans");

                    b.HasDiscriminator<string>("BlockType").HasValue("TaskDescriptionBlock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ToDoX.Core.Entity.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Tasks", "Plans");
                });

            modelBuilder.Entity("ToDoX.Core.Entity.CheckListBlock", b =>
                {
                    b.HasBaseType("ToDoX.Core.Entity.TaskDescriptionBlock");

                    b.PrimitiveCollection<List<string>>("Items")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("CheckListBlock");
                });

            modelBuilder.Entity("ToDoX.Core.Entity.CodeBlock", b =>
                {
                    b.HasBaseType("ToDoX.Core.Entity.TaskDescriptionBlock");

                    b.Property<string>("CodeContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("CodeBlock");
                });

            modelBuilder.Entity("ToDoX.Core.Entity.ImageBlock", b =>
                {
                    b.HasBaseType("ToDoX.Core.Entity.TaskDescriptionBlock");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("ImageBlock");
                });

            modelBuilder.Entity("ToDoX.Core.Entity.TextBlock", b =>
                {
                    b.HasBaseType("ToDoX.Core.Entity.TaskDescriptionBlock");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("TextBlock");
                });

            modelBuilder.Entity("ToDoX.Core.Entity.TaskDescriptionBlock", b =>
                {
                    b.HasOne("ToDoX.Core.Entity.TaskEntity", null)
                        .WithMany("Blocks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToDoX.Core.Entity.TaskEntity", b =>
                {
                    b.HasOne("ToDoX.Core.Entity.PlanEntity", null)
                        .WithMany("Tasks")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToDoX.Core.Entity.PlanEntity", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ToDoX.Core.Entity.TaskEntity", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
